FROM app:base

ENV APP_ROOT /usr/src/app
WORKDIR $APP_ROOT
COPY Gemfile $APP_ROOT
COPY Gemfile.lock $APP_ROOT

RUN \
  echo 'gem: --no-document' >> ~/.gemrc && \
  cp ~/.gemrc /etc/gemrc && \
  chmod uog+r /etc/gemrc && \
  bundle config --global build.nokogiri --use-system-libraries && \
  bundle config --global jobs 4 && \
  bundle install && \
  yarn install && \
  rm -rf ~/.gem

EXPOSE  3000
CMD ["rails", "server", "-b", "0.0.0.0"]
